-- MySQL Script generated by MySQL Workbench
-- 03/21/15 16:46:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ece356db_dctittel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ece356db_dctittel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ece356db_dctittel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ece356db_dctittel` ;

-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`Province`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`Province` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`Province` (
  `provinceID` VARCHAR(2) NOT NULL,
  `provinceName` VARCHAR(45) NULL,
  PRIMARY KEY (`provinceID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`Users` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`Users` (
  `alias` VARCHAR(30) NOT NULL,
  `password` VARCHAR(45) NULL,
  `level` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`alias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`Patient` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`Patient` (
  `alias` VARCHAR(30) NOT NULL,
  `city` VARCHAR(45) NULL,
  `provinceID` VARCHAR(2) NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`alias`),
  INDEX `province2_idx` (`provinceID` ASC),
  CONSTRAINT `province2`
    FOREIGN KEY (`provinceID`)
    REFERENCES `ece356db_dctittel`.`Province` (`provinceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user3`
    FOREIGN KEY (`alias`)
    REFERENCES `ece356db_dctittel`.`Users` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`Doctor` (
  `alias` VARCHAR(30) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `gender` INT NULL DEFAULT 0,
  `email` VARCHAR(45) NULL,
  `licenseYear` INT NULL,
  PRIMARY KEY (`alias`),
  CONSTRAINT `User2`
    FOREIGN KEY (`alias`)
    REFERENCES `ece356db_dctittel`.`Users` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`Address` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`Address` (
  `addressID` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `streetName` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `provinceID` VARCHAR(2) NULL,
  `postalCode` VARCHAR(6) NULL,
  PRIMARY KEY (`addressID`),
  INDEX `province_idx` (`provinceID` ASC),
  CONSTRAINT `province`
    FOREIGN KEY (`provinceID`)
    REFERENCES `ece356db_dctittel`.`Province` (`provinceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`Review` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`Review` (
  `reviewID` INT NOT NULL AUTO_INCREMENT,
  `reviewer` VARCHAR(30) NULL,
  `reviewee` VARCHAR(30) NULL,
  `starRating` INT NULL,
  `comments` VARCHAR(1000) NULL,
  `creationDate` DATETIME NULL,
  PRIMARY KEY (`reviewID`),
  INDEX `doctor_idx` (`reviewee` ASC),
  INDEX `patient_idx` (`reviewer` ASC),
  CONSTRAINT `doctor`
    FOREIGN KEY (`reviewee`)
    REFERENCES `ece356db_dctittel`.`Doctor` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `patient`
    FOREIGN KEY (`reviewer`)
    REFERENCES `ece356db_dctittel`.`Patient` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`Friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`Friend` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`Friend` (
  `Requester` VARCHAR(30) NOT NULL,
  `Requestee` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Requester`, `Requestee`),
  CONSTRAINT `Users`
    FOREIGN KEY (`Requester`)
    REFERENCES `ece356db_dctittel`.`Patient` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`Requestee`)
    REFERENCES `ece356db_dctittel`.`Patient` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`Specialization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`Specialization` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`Specialization` (
  `specializationID` INT NOT NULL AUTO_INCREMENT,
  `specializationName` VARCHAR(45) NULL,
  PRIMARY KEY (`specializationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`hasAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`hasAddress` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`hasAddress` (
  `alias` VARCHAR(30) NOT NULL,
  `hasAddress` INT NOT NULL,
  PRIMARY KEY (`alias`, `hasAddress`),
  INDEX `Address_idx` (`hasAddress` ASC),
  CONSTRAINT `Alias2`
    FOREIGN KEY (`alias`)
    REFERENCES `ece356db_dctittel`.`Doctor` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Address`
    FOREIGN KEY (`hasAddress`)
    REFERENCES `ece356db_dctittel`.`Address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece356db_dctittel`.`hasSpecialization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece356db_dctittel`.`hasSpecialization` ;

CREATE TABLE IF NOT EXISTS `ece356db_dctittel`.`hasSpecialization` (
  `alias` VARCHAR(30) NOT NULL,
  `hasSpecialization` INT NOT NULL,
  PRIMARY KEY (`alias`, `hasSpecialization`),
  INDEX `Address0_idx` (`hasSpecialization` ASC),
  CONSTRAINT `Alias0`
    FOREIGN KEY (`alias`)
    REFERENCES `ece356db_dctittel`.`Doctor` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Address0`
    FOREIGN KEY (`hasSpecialization`)
    REFERENCES `ece356db_dctittel`.`Specialization` (`specializationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
